name: Python deeplearning package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install OS packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pre-commit \
                                  libbz2-dev libffi-dev liblzma-dev \
                                  libsnappy-dev libsqlite3-dev \
                                  libssl-dev python3-dev python3-pip
      - name: Install Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python modules
        run: |
          make install
      - name: Run lint checks
        run: |
          make pre-commit
      - name: Test the package
        run: |
          make test
